extensions:
  health_check:
  sigv4auth:
    region: $AWS_REGION

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  awsecscontainermetrics:

  # prometheus:
  #   config:
  #     scrape_configs:
  #     - job_name: 'otel-collector'
  #       scrape_interval: 10s
  #       static_configs:
  #       - targets: ['0.0.0.0:8888']

  # Data sources: metrics
  # hostmetrics:
  #   scrapers:
  #     cpu:
  #     disk:
  #     filesystem:
  #     load:
  #     memory:
  #     network:
  #     process:
  #     processes:
  #     paging:

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s
  resourcedetection:
    detectors:
      - env
      - system
      - ecs
      - ec2
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.reserved
          - ecs.task.memory.utilized
          - ecs.task.cpu.reserved
          - ecs.task.cpu.utilized
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
          - container.duration

exporters:
  awsxray:
  debug:
    verbosity: detailed
  # prometheus:
  #   endpoint: localhost:9090
  #   namespace: default
  #   resource_to_telemetry_conversion:
  #     enabled: true
  prometheusremotewrite:
    endpoint: $AWS_PROMETHEUS_ENDPOINT
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch/traces]
      exporters: [debug, awsxray]
    metrics/app:
      receivers: [otlp]
      processors: [resourcedetection, batch/metrics]
      exporters: [debug, prometheusremotewrite]
    metrics:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [prometheusremotewrite]
    # logs:
    #   receivers: [otlp]
    #   exporters: [debug]

  extensions: [health_check, sigv4auth]
